version: "3"
services:
  web:
    env_file: .env
    container_name: user_api_django_web
    build: .
    depends_on:
      - db
    links:
      - db
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - .:/code
    command: python3 manage.py runserver 0.0.0.0:3000
  db:
    container_name: user_api_django_db
    image: mysql:8.0.2
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
